# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manu's Blog
email: me@manuchandel.com
description: > # this means to ignore newlines until "baseurl:"
  A Computer Science blog by Manu Chandel, Student at IIT Roorkee.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.manuchandel.com" # the base hostname & protocol for your site

#avatar
avatar: /assets/img/avatar.jpg
#social
facebook: myself.manuchandel
twitter: manuchandel_
github:  manuchandel

#scripts
disqus_shortname : manuchandel
google_analytics : UA-66656420-1

#navigation
navigation:
 - title: Blog
   url: /blog.html
 - title: Projects
   url: /projects.html
 - title: Notes
   url: /notes.html
 - title: About
   url: http://about.me/manuchandel

# Build settings
markdown: kramdown
